from distutils.core import setup
setup(
    name = 'PyEntrezId',
    packages = ['PyEntrezId'],
    version = '1.5.0',
    description = 'Converts UniProt, HGNC, and Ensembl Transcript Ids to Entrez Gene Id. Also, converts accession number to Taxonomy id',
    author = 'Larry Gray',
    author_email = 'lwgray@gmail.com',
    url = 'https://github.com/lwgray/pyEntrezId',
    download_url = 'https://github.com/lwgray/pyEntrezId/tarball/1.5.0',
    keywords = ['Ensembl', 'Entrez', 'Gene', 'HGNC', 'UniProt', 'Taxid', 'Accession', 'Taxonomy', 'Accesion Number', 'NCBI', 'NLM', 'DNA'],
    classifiers=[
          'Development Status :: 4 - Beta',
          'Environment :: Console',
          'Environment :: Web Environment',
          'Intended Audience :: Developerd',
          'License :: The MIT License',
          'Operating System :: OS Independent',
          'Programming Language :: Python :: 2',
          'Programming Language :: Python :: 2.6',
          'Programming Language :: Python :: 2.7',
          'Programming Language :: Python :: 3',
          'Programming Language :: Python :: 3.4',
          'Programming Language :: Python :: 3.5',
          'Programming Language :: Python',
          'Topic :: BioInformatics :: Tools',
          ],
    install_requires = ['xmltodict>=0.9.2', 'requests>=2.8.1'],
)
